apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sidecar-deployment
  labels:
    app: nginx-sidecar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sidecar
  template:
    metadata:
      labels:
        app: nginx-sidecar
    spec:
      volumes:
      - name: nginx-logs
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.15.0
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "50m"